version: '3.8'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://vault:8200"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      - hashi_wallet

  hashi-api:
    image: hashi-api
    container_name: hashi-api
    ports:
      - "8081:8081"
    depends_on:
      - vault
    networks:
      - hashi_wallet

networks:
  hashi_wallet:
    driver: bridge
