services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
      - vault_data:/vault/data
      # - ./vault-seal-keys.json:/vault/file/vault-seal-keys.json
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    environment:
      VAULT_BASE_URL: "http://vault:8200"
    networks:
      - wallet

  hashi-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hashi-api-dev
    container_name: hashi-api
    restart: always
    working_dir: /opt/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - vault_data:/vault/data
      - ./vault-seal-keys.json:/vault/file/vault-seal-keys.json
    depends_on:
      - vault
    networks:
      - wallet

volumes:
  vault_data:
    driver: local

networks:
  wallet:
    external: false
    driver: bridge
